.TH LIBRED_TERM_COLOUR 3 LIBRED
.SH NAME
libred_term_colour \- Deallocate resources required by libred_get_colour(3)
.SH SYNOPSIS
.nf
#include <libred.h>

void \fBlibred_term_colour\fP(void);
.fi
.PP
Link with
.IR -lred .
.SH DESCRIPTION
.B libred_term_colour
deallocates all resources acquired by
.BR libred_init_colour (3).
It is highly recommended to call this function before calling an
.BR exec (3)-function.
If you want to use
.BR libred_get_colour (3)
again after a call to this function has been made, you must first call
.BR libred_init_colour (3).
.SH "RETURN VALUE"
None.
.SH ERRORS
None.
.SH "FUTURE DIRECTIONS"
None.
.SH "SEE ALSO"
.BR libred.h (0),
.BR libred (7),
.BR libred_get_colour (3),
.BR libred_init_colour (3)
