@node Overview
@chapter Overview

@command{libred} is a C library that can be used to calculate
the Sun's apparent elevation, and colour temperatures, the
colour of blackbodies.

To use @command{libred}, include the header file
@file{<libred.h>}, and link with @option{-lred}. The
@command{libred} package includes a @command{librarian}
file and a @command{pkgconfig} file, both named
@command{libred}.

