@node Variables
@chapter Variables

@file{<libred.h>} defines the variable
@example
extern int libred_fd
@end example
@indent
which is either @code{-1} or the file descriptor the
library uses to access the colour temperature lookup
table. The header also defines @code{LIBRED_HAVE_FD}.
It is possible that @code{libred_fd} is removed in a
future version. If it is, @code{LIBRED_HAVE_FD} will
be removed too.

