.TH LIBRED_CHECK_TIMETRAVEL 3 LIBRED
.SH NAME
libred_check_timetravel \- Exit the process if the clock is too far in the past
.SH SYNOPSIS
.nf
#include <libred.h>

int \fBlibred_check_timetravel\fP(void);
.fi
.PP
Link with
.IR -lred .
.SH DESCRIPTION
The
.BR libred_check_timetravel ()
function exits the process if
.B libred
is not compiled to support the current time, which is the case
if it was compiled without
.I \-DTIMETRAVELLER
and the clock is before year 2000.5 in the Julian calendar. Before
exiting, the function will print an informative error message to
standard error.
.SH RETURN VALUE
Upon successful completion, without time incompatibility, the function
.BR libred_check_timetravel ()
returns 0. On failure, the function returns -1 and sets
.I errno
to indicate the error.
.SH ERRORS
The function may fail for any reason specified for
.BR clock_gettime (3).
.SH SEE ALSO
.BR libred.h (0),
.BR libred (7),
.BR libred_solar_elevation (3)
