.TH LIBRED 7 LIBRED
.SH NAME
libred \- Solar elevation and blackbody colour calculation
.SH DESCRIPTION
.B libred
is a C library for calculating the Sun's apparent elevation
and colours temperatures.
.SH SEE ALSO
.BR libred.h (0),
.BR solar-python (7),
.BR redshift (1),
.BR blueshift (1),
.BR libgamma (7)
