.TH LIBRED_term_COLOUR 3 LIBRED
.SH NAME
libred_term_colour \- Deallocate resources required by libred_get_colour(3)
.SH SYNOPSIS
.nf
#include <libred.h>

void \fBlibred_term_colour\fP(void);
.fi
.PP
Link with
.IR -lred .
.SH DESCRIPTION
.B libred_term_colour
deallocates all resources acquired by
.BR libred_init_colour (3).
It is highly recommended to call this function before calling an
.BR exec (3)-function.
If you want to use
.BR libred_get_colour (3)
again after a call to this function has been made, you must first call
.BR libred_init_colour (3).
.SH "RETURN VALUE"
None.
.SH ERRORS
None.
.SH "FUTURE DIRECTIONS"
None.
.SH "SEE ALSO"
.BR libred.h (0),
.BR libred (7),
.BR libred_get_colour (3),
.BR libred_init_colour (3)
.SH LICENSE
Copyright \(co 2016  Mattias Andrée
.br
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
.PP
Copying and distribution of this manual, with or without modification,
are permitted in any medium without royalty provided the copyright
notice and this notice are preserved.  This file is offered as-is,
without any warranty.
.SH BUGS
Please report bugs to <https://github.com/maandree/libred/issues>
or to <maandree@member.fsf.org>.

